# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_sdk.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_sdk.proto',
  package='robot_sdk.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0frobot_sdk.proto\x12\x0crobot_sdk.pb\"\xc0\x02\n\nRobotState\x12\x0e\n\x06q_abad\x18\x01 \x03(\x02\x12\r\n\x05q_hip\x18\x02 \x03(\x02\x12\x0e\n\x06q_knee\x18\x03 \x03(\x02\x12\x0f\n\x07qd_abad\x18\x04 \x03(\x02\x12\x0e\n\x06qd_hip\x18\x05 \x03(\x02\x12\x0f\n\x07qd_knee\x18\x06 \x03(\x02\x12\x12\n\nomega_body\x18\x07 \x03(\x02\x12\x13\n\x0btau_abad_fb\x18\x08 \x03(\x02\x12\x12\n\ntau_hip_fb\x18\t \x03(\x02\x12\x13\n\x0btau_knee_fb\x18\n \x03(\x02\x12\x10\n\x08position\x18\x0b \x03(\x02\x12\x0e\n\x06tau_ff\x18\x0c \x03(\x02\x12\x0c\n\x04quat\x18\r \x03(\x02\x12\x0c\n\x04gyro\x18\x0e \x03(\x02\x12\x0b\n\x03\x61\x63\x63\x18\x0f \x03(\x02\x12\x12\n\ntime_stamp\x18\x11 \x01(\x04\x12\x0b\n\x03rpy\x18\x13 \x03(\x02\x12\x13\n\x0bomega_world\x18\x14 \x03(\x02\"\x85\x03\n\x08RobotCmd\x12\x12\n\nq_des_abad\x18\x01 \x03(\x02\x12\x11\n\tq_des_hip\x18\x02 \x03(\x02\x12\x12\n\nq_des_knee\x18\x03 \x03(\x02\x12\x13\n\x0bqd_des_abad\x18\x04 \x03(\x02\x12\x12\n\nqd_des_hip\x18\x05 \x03(\x02\x12\x13\n\x0bqd_des_knee\x18\x06 \x03(\x02\x12\x13\n\x0btau_abad_ff\x18\x07 \x03(\x02\x12\x12\n\ntau_hip_ff\x18\x08 \x03(\x02\x12\x0f\n\x07kp_abad\x18\t \x03(\x02\x12\x0e\n\x06kp_hip\x18\n \x03(\x02\x12\x0f\n\x07kp_knee\x18\x0b \x03(\x02\x12\x0f\n\x07kd_abad\x18\x0c \x03(\x02\x12\x0e\n\x06kd_hip\x18\r \x03(\x02\x12\x0f\n\x07kd_knee\x18\x0e \x03(\x02\x12\x0f\n\x07kp_foot\x18\x0f \x03(\x02\x12\x0f\n\x07kd_foot\x18\x10 \x03(\x02\x12\x12\n\nq_des_foot\x18\x11 \x03(\x02\x12\x13\n\x0bqd_des_foot\x18\x12 \x03(\x02\x12\x13\n\x0btau_foot_fb\x18\x13 \x03(\x02\x12\x13\n\x0btau_foot_ff\x18\x14 \x03(\x02\x62\x06proto3'
)




_ROBOTSTATE = _descriptor.Descriptor(
  name='RobotState',
  full_name='robot_sdk.pb.RobotState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='q_abad', full_name='robot_sdk.pb.RobotState.q_abad', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_hip', full_name='robot_sdk.pb.RobotState.q_hip', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_knee', full_name='robot_sdk.pb.RobotState.q_knee', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qd_abad', full_name='robot_sdk.pb.RobotState.qd_abad', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qd_hip', full_name='robot_sdk.pb.RobotState.qd_hip', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qd_knee', full_name='robot_sdk.pb.RobotState.qd_knee', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='omega_body', full_name='robot_sdk.pb.RobotState.omega_body', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau_abad_fb', full_name='robot_sdk.pb.RobotState.tau_abad_fb', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau_hip_fb', full_name='robot_sdk.pb.RobotState.tau_hip_fb', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau_knee_fb', full_name='robot_sdk.pb.RobotState.tau_knee_fb', index=9,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='robot_sdk.pb.RobotState.position', index=10,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau_ff', full_name='robot_sdk.pb.RobotState.tau_ff', index=11,
      number=12, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quat', full_name='robot_sdk.pb.RobotState.quat', index=12,
      number=13, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro', full_name='robot_sdk.pb.RobotState.gyro', index=13,
      number=14, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acc', full_name='robot_sdk.pb.RobotState.acc', index=14,
      number=15, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='robot_sdk.pb.RobotState.time_stamp', index=15,
      number=17, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rpy', full_name='robot_sdk.pb.RobotState.rpy', index=16,
      number=19, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='omega_world', full_name='robot_sdk.pb.RobotState.omega_world', index=17,
      number=20, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=354,
)


_ROBOTCMD = _descriptor.Descriptor(
  name='RobotCmd',
  full_name='robot_sdk.pb.RobotCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='q_des_abad', full_name='robot_sdk.pb.RobotCmd.q_des_abad', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_des_hip', full_name='robot_sdk.pb.RobotCmd.q_des_hip', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_des_knee', full_name='robot_sdk.pb.RobotCmd.q_des_knee', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qd_des_abad', full_name='robot_sdk.pb.RobotCmd.qd_des_abad', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qd_des_hip', full_name='robot_sdk.pb.RobotCmd.qd_des_hip', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qd_des_knee', full_name='robot_sdk.pb.RobotCmd.qd_des_knee', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau_abad_ff', full_name='robot_sdk.pb.RobotCmd.tau_abad_ff', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau_hip_ff', full_name='robot_sdk.pb.RobotCmd.tau_hip_ff', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kp_abad', full_name='robot_sdk.pb.RobotCmd.kp_abad', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kp_hip', full_name='robot_sdk.pb.RobotCmd.kp_hip', index=9,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kp_knee', full_name='robot_sdk.pb.RobotCmd.kp_knee', index=10,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kd_abad', full_name='robot_sdk.pb.RobotCmd.kd_abad', index=11,
      number=12, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kd_hip', full_name='robot_sdk.pb.RobotCmd.kd_hip', index=12,
      number=13, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kd_knee', full_name='robot_sdk.pb.RobotCmd.kd_knee', index=13,
      number=14, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kp_foot', full_name='robot_sdk.pb.RobotCmd.kp_foot', index=14,
      number=15, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kd_foot', full_name='robot_sdk.pb.RobotCmd.kd_foot', index=15,
      number=16, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q_des_foot', full_name='robot_sdk.pb.RobotCmd.q_des_foot', index=16,
      number=17, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qd_des_foot', full_name='robot_sdk.pb.RobotCmd.qd_des_foot', index=17,
      number=18, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau_foot_fb', full_name='robot_sdk.pb.RobotCmd.tau_foot_fb', index=18,
      number=19, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tau_foot_ff', full_name='robot_sdk.pb.RobotCmd.tau_foot_ff', index=19,
      number=20, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=746,
)

DESCRIPTOR.message_types_by_name['RobotState'] = _ROBOTSTATE
DESCRIPTOR.message_types_by_name['RobotCmd'] = _ROBOTCMD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotState = _reflection.GeneratedProtocolMessageType('RobotState', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTSTATE,
  '__module__' : 'robot_sdk_pb2'
  # @@protoc_insertion_point(class_scope:robot_sdk.pb.RobotState)
  })
_sym_db.RegisterMessage(RobotState)

RobotCmd = _reflection.GeneratedProtocolMessageType('RobotCmd', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCMD,
  '__module__' : 'robot_sdk_pb2'
  # @@protoc_insertion_point(class_scope:robot_sdk.pb.RobotCmd)
  })
_sym_db.RegisterMessage(RobotCmd)


# @@protoc_insertion_point(module_scope)
