// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_sdk.proto

#include "robot_sdk.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace robot_sdk {
namespace pb {
class RobotStateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RobotState> _instance;
} _RobotState_default_instance_;
class RobotCmdDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RobotCmd> _instance;
} _RobotCmd_default_instance_;
}  // namespace pb
}  // namespace robot_sdk
static void InitDefaultsscc_info_RobotCmd_robot_5fsdk_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::robot_sdk::pb::_RobotCmd_default_instance_;
    new (ptr) ::robot_sdk::pb::RobotCmd();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::robot_sdk::pb::RobotCmd::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RobotCmd_robot_5fsdk_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RobotCmd_robot_5fsdk_2eproto}, {}};

static void InitDefaultsscc_info_RobotState_robot_5fsdk_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::robot_sdk::pb::_RobotState_default_instance_;
    new (ptr) ::robot_sdk::pb::RobotState();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::robot_sdk::pb::RobotState::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RobotState_robot_5fsdk_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RobotState_robot_5fsdk_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_robot_5fsdk_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_robot_5fsdk_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_robot_5fsdk_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_robot_5fsdk_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, q_abad_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, q_hip_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, q_knee_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, qd_abad_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, qd_hip_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, qd_knee_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, omega_body_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, tau_abad_fb_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, tau_hip_fb_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, tau_knee_fb_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, position_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, tau_ff_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, quat_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, gyro_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, acc_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, time_stamp_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, rpy_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotState, omega_world_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, q_des_abad_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, q_des_hip_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, q_des_knee_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, qd_des_abad_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, qd_des_hip_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, qd_des_knee_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, tau_abad_ff_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, tau_hip_ff_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, kp_abad_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, kp_hip_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, kp_knee_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, kd_abad_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, kd_hip_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, kd_knee_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, kp_foot_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, kd_foot_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, q_des_foot_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, qd_des_foot_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, tau_foot_fb_),
  PROTOBUF_FIELD_OFFSET(::robot_sdk::pb::RobotCmd, tau_foot_ff_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::robot_sdk::pb::RobotState)},
  { 23, -1, sizeof(::robot_sdk::pb::RobotCmd)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::robot_sdk::pb::_RobotState_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::robot_sdk::pb::_RobotCmd_default_instance_),
};

const char descriptor_table_protodef_robot_5fsdk_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017robot_sdk.proto\022\014robot_sdk.pb\"\300\002\n\nRobo"
  "tState\022\016\n\006q_abad\030\001 \003(\002\022\r\n\005q_hip\030\002 \003(\002\022\016\n"
  "\006q_knee\030\003 \003(\002\022\017\n\007qd_abad\030\004 \003(\002\022\016\n\006qd_hip"
  "\030\005 \003(\002\022\017\n\007qd_knee\030\006 \003(\002\022\022\n\nomega_body\030\007 "
  "\003(\002\022\023\n\013tau_abad_fb\030\010 \003(\002\022\022\n\ntau_hip_fb\030\t"
  " \003(\002\022\023\n\013tau_knee_fb\030\n \003(\002\022\020\n\010position\030\013 "
  "\003(\002\022\016\n\006tau_ff\030\014 \003(\002\022\014\n\004quat\030\r \003(\002\022\014\n\004gyr"
  "o\030\016 \003(\002\022\013\n\003acc\030\017 \003(\002\022\022\n\ntime_stamp\030\021 \001(\004"
  "\022\013\n\003rpy\030\023 \003(\002\022\023\n\013omega_world\030\024 \003(\002\"\205\003\n\010R"
  "obotCmd\022\022\n\nq_des_abad\030\001 \003(\002\022\021\n\tq_des_hip"
  "\030\002 \003(\002\022\022\n\nq_des_knee\030\003 \003(\002\022\023\n\013qd_des_aba"
  "d\030\004 \003(\002\022\022\n\nqd_des_hip\030\005 \003(\002\022\023\n\013qd_des_kn"
  "ee\030\006 \003(\002\022\023\n\013tau_abad_ff\030\007 \003(\002\022\022\n\ntau_hip"
  "_ff\030\010 \003(\002\022\017\n\007kp_abad\030\t \003(\002\022\016\n\006kp_hip\030\n \003"
  "(\002\022\017\n\007kp_knee\030\013 \003(\002\022\017\n\007kd_abad\030\014 \003(\002\022\016\n\006"
  "kd_hip\030\r \003(\002\022\017\n\007kd_knee\030\016 \003(\002\022\017\n\007kp_foot"
  "\030\017 \003(\002\022\017\n\007kd_foot\030\020 \003(\002\022\022\n\nq_des_foot\030\021 "
  "\003(\002\022\023\n\013qd_des_foot\030\022 \003(\002\022\023\n\013tau_foot_fb\030"
  "\023 \003(\002\022\023\n\013tau_foot_ff\030\024 \003(\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_robot_5fsdk_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_robot_5fsdk_2eproto_sccs[2] = {
  &scc_info_RobotCmd_robot_5fsdk_2eproto.base,
  &scc_info_RobotState_robot_5fsdk_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_robot_5fsdk_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_robot_5fsdk_2eproto = {
  false, false, descriptor_table_protodef_robot_5fsdk_2eproto, "robot_sdk.proto", 754,
  &descriptor_table_robot_5fsdk_2eproto_once, descriptor_table_robot_5fsdk_2eproto_sccs, descriptor_table_robot_5fsdk_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_robot_5fsdk_2eproto::offsets,
  file_level_metadata_robot_5fsdk_2eproto, 2, file_level_enum_descriptors_robot_5fsdk_2eproto, file_level_service_descriptors_robot_5fsdk_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_robot_5fsdk_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_robot_5fsdk_2eproto)), true);
namespace robot_sdk {
namespace pb {

// ===================================================================

void RobotState::InitAsDefaultInstance() {
}
class RobotState::_Internal {
 public:
};

RobotState::RobotState(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  q_abad_(arena),
  q_hip_(arena),
  q_knee_(arena),
  qd_abad_(arena),
  qd_hip_(arena),
  qd_knee_(arena),
  omega_body_(arena),
  tau_abad_fb_(arena),
  tau_hip_fb_(arena),
  tau_knee_fb_(arena),
  position_(arena),
  tau_ff_(arena),
  quat_(arena),
  gyro_(arena),
  acc_(arena),
  rpy_(arena),
  omega_world_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:robot_sdk.pb.RobotState)
}
RobotState::RobotState(const RobotState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      q_abad_(from.q_abad_),
      q_hip_(from.q_hip_),
      q_knee_(from.q_knee_),
      qd_abad_(from.qd_abad_),
      qd_hip_(from.qd_hip_),
      qd_knee_(from.qd_knee_),
      omega_body_(from.omega_body_),
      tau_abad_fb_(from.tau_abad_fb_),
      tau_hip_fb_(from.tau_hip_fb_),
      tau_knee_fb_(from.tau_knee_fb_),
      position_(from.position_),
      tau_ff_(from.tau_ff_),
      quat_(from.quat_),
      gyro_(from.gyro_),
      acc_(from.acc_),
      rpy_(from.rpy_),
      omega_world_(from.omega_world_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  time_stamp_ = from.time_stamp_;
  // @@protoc_insertion_point(copy_constructor:robot_sdk.pb.RobotState)
}

void RobotState::SharedCtor() {
  time_stamp_ = PROTOBUF_ULONGLONG(0);
}

RobotState::~RobotState() {
  // @@protoc_insertion_point(destructor:robot_sdk.pb.RobotState)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RobotState::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void RobotState::ArenaDtor(void* object) {
  RobotState* _this = reinterpret_cast< RobotState* >(object);
  (void)_this;
}
void RobotState::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RobotState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RobotState& RobotState::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RobotState_robot_5fsdk_2eproto.base);
  return *internal_default_instance();
}


void RobotState::Clear() {
// @@protoc_insertion_point(message_clear_start:robot_sdk.pb.RobotState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  q_abad_.Clear();
  q_hip_.Clear();
  q_knee_.Clear();
  qd_abad_.Clear();
  qd_hip_.Clear();
  qd_knee_.Clear();
  omega_body_.Clear();
  tau_abad_fb_.Clear();
  tau_hip_fb_.Clear();
  tau_knee_fb_.Clear();
  position_.Clear();
  tau_ff_.Clear();
  quat_.Clear();
  gyro_.Clear();
  acc_.Clear();
  rpy_.Clear();
  omega_world_.Clear();
  time_stamp_ = PROTOBUF_ULONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RobotState::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated float q_abad = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_q_abad(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13) {
          _internal_add_q_abad(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float q_hip = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_q_hip(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21) {
          _internal_add_q_hip(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float q_knee = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_q_knee(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29) {
          _internal_add_q_knee(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float qd_abad = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_qd_abad(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37) {
          _internal_add_qd_abad(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float qd_hip = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_qd_hip(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45) {
          _internal_add_qd_hip(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float qd_knee = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_qd_knee(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53) {
          _internal_add_qd_knee(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float omega_body = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_omega_body(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61) {
          _internal_add_omega_body(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float tau_abad_fb = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_tau_abad_fb(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69) {
          _internal_add_tau_abad_fb(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float tau_hip_fb = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_tau_hip_fb(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 77) {
          _internal_add_tau_hip_fb(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float tau_knee_fb = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_tau_knee_fb(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 85) {
          _internal_add_tau_knee_fb(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float position = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_position(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 93) {
          _internal_add_position(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float tau_ff = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_tau_ff(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 101) {
          _internal_add_tau_ff(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float quat = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_quat(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 109) {
          _internal_add_quat(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float gyro = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_gyro(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 117) {
          _internal_add_gyro(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float acc = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 122)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_acc(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 125) {
          _internal_add_acc(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // uint64 time_stamp = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 136)) {
          time_stamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated float rpy = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 154)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_rpy(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 157) {
          _internal_add_rpy(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float omega_world = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_omega_world(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 165) {
          _internal_add_omega_world(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RobotState::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:robot_sdk.pb.RobotState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float q_abad = 1;
  if (this->_internal_q_abad_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_q_abad(), target);
  }

  // repeated float q_hip = 2;
  if (this->_internal_q_hip_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_q_hip(), target);
  }

  // repeated float q_knee = 3;
  if (this->_internal_q_knee_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_q_knee(), target);
  }

  // repeated float qd_abad = 4;
  if (this->_internal_qd_abad_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_qd_abad(), target);
  }

  // repeated float qd_hip = 5;
  if (this->_internal_qd_hip_size() > 0) {
    target = stream->WriteFixedPacked(5, _internal_qd_hip(), target);
  }

  // repeated float qd_knee = 6;
  if (this->_internal_qd_knee_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_qd_knee(), target);
  }

  // repeated float omega_body = 7;
  if (this->_internal_omega_body_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_omega_body(), target);
  }

  // repeated float tau_abad_fb = 8;
  if (this->_internal_tau_abad_fb_size() > 0) {
    target = stream->WriteFixedPacked(8, _internal_tau_abad_fb(), target);
  }

  // repeated float tau_hip_fb = 9;
  if (this->_internal_tau_hip_fb_size() > 0) {
    target = stream->WriteFixedPacked(9, _internal_tau_hip_fb(), target);
  }

  // repeated float tau_knee_fb = 10;
  if (this->_internal_tau_knee_fb_size() > 0) {
    target = stream->WriteFixedPacked(10, _internal_tau_knee_fb(), target);
  }

  // repeated float position = 11;
  if (this->_internal_position_size() > 0) {
    target = stream->WriteFixedPacked(11, _internal_position(), target);
  }

  // repeated float tau_ff = 12;
  if (this->_internal_tau_ff_size() > 0) {
    target = stream->WriteFixedPacked(12, _internal_tau_ff(), target);
  }

  // repeated float quat = 13;
  if (this->_internal_quat_size() > 0) {
    target = stream->WriteFixedPacked(13, _internal_quat(), target);
  }

  // repeated float gyro = 14;
  if (this->_internal_gyro_size() > 0) {
    target = stream->WriteFixedPacked(14, _internal_gyro(), target);
  }

  // repeated float acc = 15;
  if (this->_internal_acc_size() > 0) {
    target = stream->WriteFixedPacked(15, _internal_acc(), target);
  }

  // uint64 time_stamp = 17;
  if (this->time_stamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(17, this->_internal_time_stamp(), target);
  }

  // repeated float rpy = 19;
  if (this->_internal_rpy_size() > 0) {
    target = stream->WriteFixedPacked(19, _internal_rpy(), target);
  }

  // repeated float omega_world = 20;
  if (this->_internal_omega_world_size() > 0) {
    target = stream->WriteFixedPacked(20, _internal_omega_world(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:robot_sdk.pb.RobotState)
  return target;
}

size_t RobotState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:robot_sdk.pb.RobotState)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float q_abad = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_q_abad_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _q_abad_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float q_hip = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_q_hip_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _q_hip_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float q_knee = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_q_knee_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _q_knee_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float qd_abad = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_qd_abad_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _qd_abad_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float qd_hip = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_qd_hip_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _qd_hip_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float qd_knee = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_qd_knee_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _qd_knee_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float omega_body = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_omega_body_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _omega_body_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float tau_abad_fb = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_tau_abad_fb_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tau_abad_fb_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float tau_hip_fb = 9;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_tau_hip_fb_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tau_hip_fb_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float tau_knee_fb = 10;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_tau_knee_fb_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tau_knee_fb_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float position = 11;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_position_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _position_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float tau_ff = 12;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_tau_ff_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tau_ff_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float quat = 13;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_quat_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _quat_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float gyro = 14;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_gyro_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _gyro_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float acc = 15;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_acc_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _acc_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float rpy = 19;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_rpy_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _rpy_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float omega_world = 20;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_omega_world_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _omega_world_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // uint64 time_stamp = 17;
  if (this->time_stamp() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_time_stamp());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RobotState::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:robot_sdk.pb.RobotState)
  GOOGLE_DCHECK_NE(&from, this);
  const RobotState* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RobotState>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:robot_sdk.pb.RobotState)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:robot_sdk.pb.RobotState)
    MergeFrom(*source);
  }
}

void RobotState::MergeFrom(const RobotState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:robot_sdk.pb.RobotState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  q_abad_.MergeFrom(from.q_abad_);
  q_hip_.MergeFrom(from.q_hip_);
  q_knee_.MergeFrom(from.q_knee_);
  qd_abad_.MergeFrom(from.qd_abad_);
  qd_hip_.MergeFrom(from.qd_hip_);
  qd_knee_.MergeFrom(from.qd_knee_);
  omega_body_.MergeFrom(from.omega_body_);
  tau_abad_fb_.MergeFrom(from.tau_abad_fb_);
  tau_hip_fb_.MergeFrom(from.tau_hip_fb_);
  tau_knee_fb_.MergeFrom(from.tau_knee_fb_);
  position_.MergeFrom(from.position_);
  tau_ff_.MergeFrom(from.tau_ff_);
  quat_.MergeFrom(from.quat_);
  gyro_.MergeFrom(from.gyro_);
  acc_.MergeFrom(from.acc_);
  rpy_.MergeFrom(from.rpy_);
  omega_world_.MergeFrom(from.omega_world_);
  if (from.time_stamp() != 0) {
    _internal_set_time_stamp(from._internal_time_stamp());
  }
}

void RobotState::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:robot_sdk.pb.RobotState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RobotState::CopyFrom(const RobotState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:robot_sdk.pb.RobotState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotState::IsInitialized() const {
  return true;
}

void RobotState::InternalSwap(RobotState* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  q_abad_.InternalSwap(&other->q_abad_);
  q_hip_.InternalSwap(&other->q_hip_);
  q_knee_.InternalSwap(&other->q_knee_);
  qd_abad_.InternalSwap(&other->qd_abad_);
  qd_hip_.InternalSwap(&other->qd_hip_);
  qd_knee_.InternalSwap(&other->qd_knee_);
  omega_body_.InternalSwap(&other->omega_body_);
  tau_abad_fb_.InternalSwap(&other->tau_abad_fb_);
  tau_hip_fb_.InternalSwap(&other->tau_hip_fb_);
  tau_knee_fb_.InternalSwap(&other->tau_knee_fb_);
  position_.InternalSwap(&other->position_);
  tau_ff_.InternalSwap(&other->tau_ff_);
  quat_.InternalSwap(&other->quat_);
  gyro_.InternalSwap(&other->gyro_);
  acc_.InternalSwap(&other->acc_);
  rpy_.InternalSwap(&other->rpy_);
  omega_world_.InternalSwap(&other->omega_world_);
  swap(time_stamp_, other->time_stamp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RobotState::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RobotCmd::InitAsDefaultInstance() {
}
class RobotCmd::_Internal {
 public:
};

RobotCmd::RobotCmd(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  q_des_abad_(arena),
  q_des_hip_(arena),
  q_des_knee_(arena),
  qd_des_abad_(arena),
  qd_des_hip_(arena),
  qd_des_knee_(arena),
  tau_abad_ff_(arena),
  tau_hip_ff_(arena),
  kp_abad_(arena),
  kp_hip_(arena),
  kp_knee_(arena),
  kd_abad_(arena),
  kd_hip_(arena),
  kd_knee_(arena),
  kp_foot_(arena),
  kd_foot_(arena),
  q_des_foot_(arena),
  qd_des_foot_(arena),
  tau_foot_fb_(arena),
  tau_foot_ff_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:robot_sdk.pb.RobotCmd)
}
RobotCmd::RobotCmd(const RobotCmd& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      q_des_abad_(from.q_des_abad_),
      q_des_hip_(from.q_des_hip_),
      q_des_knee_(from.q_des_knee_),
      qd_des_abad_(from.qd_des_abad_),
      qd_des_hip_(from.qd_des_hip_),
      qd_des_knee_(from.qd_des_knee_),
      tau_abad_ff_(from.tau_abad_ff_),
      tau_hip_ff_(from.tau_hip_ff_),
      kp_abad_(from.kp_abad_),
      kp_hip_(from.kp_hip_),
      kp_knee_(from.kp_knee_),
      kd_abad_(from.kd_abad_),
      kd_hip_(from.kd_hip_),
      kd_knee_(from.kd_knee_),
      kp_foot_(from.kp_foot_),
      kd_foot_(from.kd_foot_),
      q_des_foot_(from.q_des_foot_),
      qd_des_foot_(from.qd_des_foot_),
      tau_foot_fb_(from.tau_foot_fb_),
      tau_foot_ff_(from.tau_foot_ff_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:robot_sdk.pb.RobotCmd)
}

void RobotCmd::SharedCtor() {
}

RobotCmd::~RobotCmd() {
  // @@protoc_insertion_point(destructor:robot_sdk.pb.RobotCmd)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RobotCmd::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void RobotCmd::ArenaDtor(void* object) {
  RobotCmd* _this = reinterpret_cast< RobotCmd* >(object);
  (void)_this;
}
void RobotCmd::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RobotCmd::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RobotCmd& RobotCmd::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RobotCmd_robot_5fsdk_2eproto.base);
  return *internal_default_instance();
}


void RobotCmd::Clear() {
// @@protoc_insertion_point(message_clear_start:robot_sdk.pb.RobotCmd)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  q_des_abad_.Clear();
  q_des_hip_.Clear();
  q_des_knee_.Clear();
  qd_des_abad_.Clear();
  qd_des_hip_.Clear();
  qd_des_knee_.Clear();
  tau_abad_ff_.Clear();
  tau_hip_ff_.Clear();
  kp_abad_.Clear();
  kp_hip_.Clear();
  kp_knee_.Clear();
  kd_abad_.Clear();
  kd_hip_.Clear();
  kd_knee_.Clear();
  kp_foot_.Clear();
  kd_foot_.Clear();
  q_des_foot_.Clear();
  qd_des_foot_.Clear();
  tau_foot_fb_.Clear();
  tau_foot_ff_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RobotCmd::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated float q_des_abad = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_q_des_abad(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13) {
          _internal_add_q_des_abad(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float q_des_hip = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_q_des_hip(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21) {
          _internal_add_q_des_hip(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float q_des_knee = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_q_des_knee(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29) {
          _internal_add_q_des_knee(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float qd_des_abad = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_qd_des_abad(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37) {
          _internal_add_qd_des_abad(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float qd_des_hip = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_qd_des_hip(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45) {
          _internal_add_qd_des_hip(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float qd_des_knee = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_qd_des_knee(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53) {
          _internal_add_qd_des_knee(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float tau_abad_ff = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_tau_abad_ff(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61) {
          _internal_add_tau_abad_ff(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float tau_hip_ff = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_tau_hip_ff(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69) {
          _internal_add_tau_hip_ff(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float kp_abad = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kp_abad(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 77) {
          _internal_add_kp_abad(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float kp_hip = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kp_hip(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 85) {
          _internal_add_kp_hip(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float kp_knee = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kp_knee(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 93) {
          _internal_add_kp_knee(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float kd_abad = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kd_abad(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 101) {
          _internal_add_kd_abad(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float kd_hip = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kd_hip(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 109) {
          _internal_add_kd_hip(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float kd_knee = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kd_knee(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 117) {
          _internal_add_kd_knee(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float kp_foot = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 122)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kp_foot(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 125) {
          _internal_add_kp_foot(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float kd_foot = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 130)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_kd_foot(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 133) {
          _internal_add_kd_foot(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float q_des_foot = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 138)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_q_des_foot(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 141) {
          _internal_add_q_des_foot(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float qd_des_foot = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 146)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_qd_des_foot(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 149) {
          _internal_add_qd_des_foot(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float tau_foot_fb = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 154)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_tau_foot_fb(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 157) {
          _internal_add_tau_foot_fb(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float tau_foot_ff = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_tau_foot_ff(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 165) {
          _internal_add_tau_foot_ff(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RobotCmd::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:robot_sdk.pb.RobotCmd)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float q_des_abad = 1;
  if (this->_internal_q_des_abad_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_q_des_abad(), target);
  }

  // repeated float q_des_hip = 2;
  if (this->_internal_q_des_hip_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_q_des_hip(), target);
  }

  // repeated float q_des_knee = 3;
  if (this->_internal_q_des_knee_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_q_des_knee(), target);
  }

  // repeated float qd_des_abad = 4;
  if (this->_internal_qd_des_abad_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_qd_des_abad(), target);
  }

  // repeated float qd_des_hip = 5;
  if (this->_internal_qd_des_hip_size() > 0) {
    target = stream->WriteFixedPacked(5, _internal_qd_des_hip(), target);
  }

  // repeated float qd_des_knee = 6;
  if (this->_internal_qd_des_knee_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_qd_des_knee(), target);
  }

  // repeated float tau_abad_ff = 7;
  if (this->_internal_tau_abad_ff_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_tau_abad_ff(), target);
  }

  // repeated float tau_hip_ff = 8;
  if (this->_internal_tau_hip_ff_size() > 0) {
    target = stream->WriteFixedPacked(8, _internal_tau_hip_ff(), target);
  }

  // repeated float kp_abad = 9;
  if (this->_internal_kp_abad_size() > 0) {
    target = stream->WriteFixedPacked(9, _internal_kp_abad(), target);
  }

  // repeated float kp_hip = 10;
  if (this->_internal_kp_hip_size() > 0) {
    target = stream->WriteFixedPacked(10, _internal_kp_hip(), target);
  }

  // repeated float kp_knee = 11;
  if (this->_internal_kp_knee_size() > 0) {
    target = stream->WriteFixedPacked(11, _internal_kp_knee(), target);
  }

  // repeated float kd_abad = 12;
  if (this->_internal_kd_abad_size() > 0) {
    target = stream->WriteFixedPacked(12, _internal_kd_abad(), target);
  }

  // repeated float kd_hip = 13;
  if (this->_internal_kd_hip_size() > 0) {
    target = stream->WriteFixedPacked(13, _internal_kd_hip(), target);
  }

  // repeated float kd_knee = 14;
  if (this->_internal_kd_knee_size() > 0) {
    target = stream->WriteFixedPacked(14, _internal_kd_knee(), target);
  }

  // repeated float kp_foot = 15;
  if (this->_internal_kp_foot_size() > 0) {
    target = stream->WriteFixedPacked(15, _internal_kp_foot(), target);
  }

  // repeated float kd_foot = 16;
  if (this->_internal_kd_foot_size() > 0) {
    target = stream->WriteFixedPacked(16, _internal_kd_foot(), target);
  }

  // repeated float q_des_foot = 17;
  if (this->_internal_q_des_foot_size() > 0) {
    target = stream->WriteFixedPacked(17, _internal_q_des_foot(), target);
  }

  // repeated float qd_des_foot = 18;
  if (this->_internal_qd_des_foot_size() > 0) {
    target = stream->WriteFixedPacked(18, _internal_qd_des_foot(), target);
  }

  // repeated float tau_foot_fb = 19;
  if (this->_internal_tau_foot_fb_size() > 0) {
    target = stream->WriteFixedPacked(19, _internal_tau_foot_fb(), target);
  }

  // repeated float tau_foot_ff = 20;
  if (this->_internal_tau_foot_ff_size() > 0) {
    target = stream->WriteFixedPacked(20, _internal_tau_foot_ff(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:robot_sdk.pb.RobotCmd)
  return target;
}

size_t RobotCmd::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:robot_sdk.pb.RobotCmd)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float q_des_abad = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_q_des_abad_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _q_des_abad_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float q_des_hip = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_q_des_hip_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _q_des_hip_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float q_des_knee = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_q_des_knee_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _q_des_knee_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float qd_des_abad = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_qd_des_abad_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _qd_des_abad_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float qd_des_hip = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_qd_des_hip_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _qd_des_hip_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float qd_des_knee = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_qd_des_knee_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _qd_des_knee_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float tau_abad_ff = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_tau_abad_ff_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tau_abad_ff_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float tau_hip_ff = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_tau_hip_ff_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tau_hip_ff_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float kp_abad = 9;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kp_abad_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _kp_abad_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float kp_hip = 10;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kp_hip_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _kp_hip_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float kp_knee = 11;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kp_knee_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _kp_knee_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float kd_abad = 12;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kd_abad_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _kd_abad_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float kd_hip = 13;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kd_hip_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _kd_hip_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float kd_knee = 14;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kd_knee_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _kd_knee_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float kp_foot = 15;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kp_foot_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _kp_foot_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float kd_foot = 16;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_kd_foot_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _kd_foot_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float q_des_foot = 17;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_q_des_foot_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _q_des_foot_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float qd_des_foot = 18;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_qd_des_foot_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _qd_des_foot_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float tau_foot_fb = 19;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_tau_foot_fb_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tau_foot_fb_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float tau_foot_ff = 20;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_tau_foot_ff_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _tau_foot_ff_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RobotCmd::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:robot_sdk.pb.RobotCmd)
  GOOGLE_DCHECK_NE(&from, this);
  const RobotCmd* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RobotCmd>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:robot_sdk.pb.RobotCmd)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:robot_sdk.pb.RobotCmd)
    MergeFrom(*source);
  }
}

void RobotCmd::MergeFrom(const RobotCmd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:robot_sdk.pb.RobotCmd)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  q_des_abad_.MergeFrom(from.q_des_abad_);
  q_des_hip_.MergeFrom(from.q_des_hip_);
  q_des_knee_.MergeFrom(from.q_des_knee_);
  qd_des_abad_.MergeFrom(from.qd_des_abad_);
  qd_des_hip_.MergeFrom(from.qd_des_hip_);
  qd_des_knee_.MergeFrom(from.qd_des_knee_);
  tau_abad_ff_.MergeFrom(from.tau_abad_ff_);
  tau_hip_ff_.MergeFrom(from.tau_hip_ff_);
  kp_abad_.MergeFrom(from.kp_abad_);
  kp_hip_.MergeFrom(from.kp_hip_);
  kp_knee_.MergeFrom(from.kp_knee_);
  kd_abad_.MergeFrom(from.kd_abad_);
  kd_hip_.MergeFrom(from.kd_hip_);
  kd_knee_.MergeFrom(from.kd_knee_);
  kp_foot_.MergeFrom(from.kp_foot_);
  kd_foot_.MergeFrom(from.kd_foot_);
  q_des_foot_.MergeFrom(from.q_des_foot_);
  qd_des_foot_.MergeFrom(from.qd_des_foot_);
  tau_foot_fb_.MergeFrom(from.tau_foot_fb_);
  tau_foot_ff_.MergeFrom(from.tau_foot_ff_);
}

void RobotCmd::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:robot_sdk.pb.RobotCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RobotCmd::CopyFrom(const RobotCmd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:robot_sdk.pb.RobotCmd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotCmd::IsInitialized() const {
  return true;
}

void RobotCmd::InternalSwap(RobotCmd* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  q_des_abad_.InternalSwap(&other->q_des_abad_);
  q_des_hip_.InternalSwap(&other->q_des_hip_);
  q_des_knee_.InternalSwap(&other->q_des_knee_);
  qd_des_abad_.InternalSwap(&other->qd_des_abad_);
  qd_des_hip_.InternalSwap(&other->qd_des_hip_);
  qd_des_knee_.InternalSwap(&other->qd_des_knee_);
  tau_abad_ff_.InternalSwap(&other->tau_abad_ff_);
  tau_hip_ff_.InternalSwap(&other->tau_hip_ff_);
  kp_abad_.InternalSwap(&other->kp_abad_);
  kp_hip_.InternalSwap(&other->kp_hip_);
  kp_knee_.InternalSwap(&other->kp_knee_);
  kd_abad_.InternalSwap(&other->kd_abad_);
  kd_hip_.InternalSwap(&other->kd_hip_);
  kd_knee_.InternalSwap(&other->kd_knee_);
  kp_foot_.InternalSwap(&other->kp_foot_);
  kd_foot_.InternalSwap(&other->kd_foot_);
  q_des_foot_.InternalSwap(&other->q_des_foot_);
  qd_des_foot_.InternalSwap(&other->qd_des_foot_);
  tau_foot_fb_.InternalSwap(&other->tau_foot_fb_);
  tau_foot_ff_.InternalSwap(&other->tau_foot_ff_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RobotCmd::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace robot_sdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::robot_sdk::pb::RobotState* Arena::CreateMaybeMessage< ::robot_sdk::pb::RobotState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::robot_sdk::pb::RobotState >(arena);
}
template<> PROTOBUF_NOINLINE ::robot_sdk::pb::RobotCmd* Arena::CreateMaybeMessage< ::robot_sdk::pb::RobotCmd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::robot_sdk::pb::RobotCmd >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
