// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file InsDataPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

#include "InsDataPubSubTypes.h"

using SerializedPayload_t = eprosima::fastrtps::rtps::SerializedPayload_t;
using InstanceHandle_t = eprosima::fastrtps::rtps::InstanceHandle_t;

namespace vehicle_msgs {
    namespace msg {
        InsDataPubSubType::InsDataPubSubType()
        {
            setName("vehicle_msgs::msg::dds_::InsData_");
            auto type_size = InsData::getMaxCdrSerializedSize();
            type_size += eprosima::fastcdr::Cdr::alignment(type_size, 4);
            m_typeSize = static_cast<uint32_t>(type_size) + 4;
            m_isGetKeyDefined = InsData::isKeyDefined();
            size_t keyLength = InsData::getKeyMaxCdrSerializedSize() > 16 ?
                    InsData::getKeyMaxCdrSerializedSize() : 16;
            m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
            memset(m_keyBuffer, 0, keyLength);
        }

        InsDataPubSubType::~InsDataPubSubType()
        {
            if (m_keyBuffer != nullptr)
                free(m_keyBuffer);
        }

        bool InsDataPubSubType::serialize(void* data, SerializedPayload_t* payload)
        {
            InsData* p_type = static_cast<InsData*>(data);
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN, eprosima::fastcdr::Cdr::DDS_CDR);
            payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            ser.serialize_encapsulation();
            try { p_type->serialize(ser); }
            catch (eprosima::fastcdr::exception::NotEnoughMemoryException&) { return false; }
            payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            return true;
        }

        bool InsDataPubSubType::deserialize(SerializedPayload_t* payload, void* data)
        {
            try
            {
                InsData* p_type = static_cast<InsData*>(data);
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN, eprosima::fastcdr::Cdr::DDS_CDR);
                deser.read_encapsulation();
                payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
                p_type->deserialize(deser);
            }
            catch (eprosima::fastcdr::exception::NotEnoughMemoryException&) { return false; }
            return true;
        }

        std::function<uint32_t()> InsDataPubSubType::getSerializedSizeProvider(void* data)
        {
            return [data]() -> uint32_t {
                return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<InsData*>(data))) + 4u;
            };
        }

        void* InsDataPubSubType::createData()
        {
            return reinterpret_cast<void*>(new InsData());
        }

        void InsDataPubSubType::deleteData(void* data)
        {
            delete(reinterpret_cast<InsData*>(data));
        }

        bool InsDataPubSubType::getKey(void* data, InstanceHandle_t* handle, bool force_md5)
        {
            if (!m_isGetKeyDefined) return false;
            InsData* p_type = static_cast<InsData*>(data);
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer), InsData::getKeyMaxCdrSerializedSize());
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS);
            p_type->serializeKey(ser);
            if (force_md5 || InsData::getKeyMaxCdrSerializedSize() > 16)
            {
                m_md5.init();
                m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
                m_md5.finalize();
                for (uint8_t i = 0; i < 16; ++i) handle->value[i] = m_md5.digest[i];
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i) handle->value[i] = m_keyBuffer[i];
            }
            return true;
        }
    }
}
