// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file InsData.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "InsData.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define vehicle_msgs_msg_std_msgs_msg_Header_max_cdr_typesize 268ULL;
#define vehicle_msgs_msg_InsData_max_cdr_typesize 400ULL;
#define vehicle_msgs_msg_std_msgs_msg_Time_max_cdr_typesize 8ULL;
#define vehicle_msgs_msg_std_msgs_msg_Header_max_key_cdr_typesize 0ULL;
#define vehicle_msgs_msg_InsData_max_key_cdr_typesize 0ULL;

vehicle_msgs::msg::InsData::InsData()
{
    m_longitude = 0.0;
    m_latitude = 0.0;
    m_altitude = 0.0f;
    m_yaw = 0.0f;
    m_pitch = 0.0f;
    m_roll = 0.0f;
    m_vx = 0.0f;
    m_vy = 0.0f;
    m_vt = 0.0f;
    m_psd = 0.0f;
    m_r = 0.0f;
    m_p = 0.0f;
    m_q = 0.0f;
    m_gps_fix_state = 0;
    m_satellite_num = 0;
    m_gps_id = 0;
    m_nav_state = 0;
    m_nav_fault_code = 0;
    m_is_valid = false;
    m_timestamp = 0.0;
}

vehicle_msgs::msg::InsData::~InsData()
{
}

vehicle_msgs::msg::InsData::InsData(const InsData& x)
{
    m_header = x.m_header;
    m_longitude = x.m_longitude;
    m_latitude = x.m_latitude;
    m_altitude = x.m_altitude;
    m_yaw = x.m_yaw;
    m_pitch = x.m_pitch;
    m_roll = x.m_roll;
    m_vx = x.m_vx;
    m_vy = x.m_vy;
    m_vt = x.m_vt;
    m_psd = x.m_psd;
    m_r = x.m_r;
    m_p = x.m_p;
    m_q = x.m_q;
    m_gps_fix_state = x.m_gps_fix_state;
    m_satellite_num = x.m_satellite_num;
    m_gps_id = x.m_gps_id;
    m_nav_state = x.m_nav_state;
    m_nav_fault_code = x.m_nav_fault_code;
    m_is_valid = x.m_is_valid;
    m_timestamp = x.m_timestamp;
}

vehicle_msgs::msg::InsData::InsData(InsData&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_longitude = x.m_longitude;
    m_latitude = x.m_latitude;
    m_altitude = x.m_altitude;
    m_yaw = x.m_yaw;
    m_pitch = x.m_pitch;
    m_roll = x.m_roll;
    m_vx = x.m_vx;
    m_vy = x.m_vy;
    m_vt = x.m_vt;
    m_psd = x.m_psd;
    m_r = x.m_r;
    m_p = x.m_p;
    m_q = x.m_q;
    m_gps_fix_state = x.m_gps_fix_state;
    m_satellite_num = x.m_satellite_num;
    m_gps_id = x.m_gps_id;
    m_nav_state = x.m_nav_state;
    m_nav_fault_code = x.m_nav_fault_code;
    m_is_valid = x.m_is_valid;
    m_timestamp = x.m_timestamp;
}

vehicle_msgs::msg::InsData& vehicle_msgs::msg::InsData::operator =(const InsData& x)
{
    m_header = x.m_header;
    m_longitude = x.m_longitude;
    m_latitude = x.m_latitude;
    m_altitude = x.m_altitude;
    m_yaw = x.m_yaw;
    m_pitch = x.m_pitch;
    m_roll = x.m_roll;
    m_vx = x.m_vx;
    m_vy = x.m_vy;
    m_vt = x.m_vt;
    m_psd = x.m_psd;
    m_r = x.m_r;
    m_p = x.m_p;
    m_q = x.m_q;
    m_gps_fix_state = x.m_gps_fix_state;
    m_satellite_num = x.m_satellite_num;
    m_gps_id = x.m_gps_id;
    m_nav_state = x.m_nav_state;
    m_nav_fault_code = x.m_nav_fault_code;
    m_is_valid = x.m_is_valid;
    m_timestamp = x.m_timestamp;
    return *this;
}

vehicle_msgs::msg::InsData& vehicle_msgs::msg::InsData::operator =(InsData&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_longitude = x.m_longitude;
    m_latitude = x.m_latitude;
    m_altitude = x.m_altitude;
    m_yaw = x.m_yaw;
    m_pitch = x.m_pitch;
    m_roll = x.m_roll;
    m_vx = x.m_vx;
    m_vy = x.m_vy;
    m_vt = x.m_vt;
    m_psd = x.m_psd;
    m_r = x.m_r;
    m_p = x.m_p;
    m_q = x.m_q;
    m_gps_fix_state = x.m_gps_fix_state;
    m_satellite_num = x.m_satellite_num;
    m_gps_id = x.m_gps_id;
    m_nav_state = x.m_nav_state;
    m_nav_fault_code = x.m_nav_fault_code;
    m_is_valid = x.m_is_valid;
    m_timestamp = x.m_timestamp;
    return *this;
}

bool vehicle_msgs::msg::InsData::operator ==(const InsData& x) const
{
    return (m_header == x.m_header &&
            m_longitude == x.m_longitude &&
            m_latitude == x.m_latitude &&
            m_altitude == x.m_altitude &&
            m_yaw == x.m_yaw &&
            m_pitch == x.m_pitch &&
            m_roll == x.m_roll &&
            m_vx == x.m_vx &&
            m_vy == x.m_vy &&
            m_vt == x.m_vt &&
            m_psd == x.m_psd &&
            m_r == x.m_r &&
            m_p == x.m_p &&
            m_q == x.m_q &&
            m_gps_fix_state == x.m_gps_fix_state &&
            m_satellite_num == x.m_satellite_num &&
            m_gps_id == x.m_gps_id &&
            m_nav_state == x.m_nav_state &&
            m_nav_fault_code == x.m_nav_fault_code &&
            m_is_valid == x.m_is_valid &&
            m_timestamp == x.m_timestamp);
}

bool vehicle_msgs::msg::InsData::operator !=(const InsData& x) const
{
    return !(*this == x);
}

size_t vehicle_msgs::msg::InsData::getMaxCdrSerializedSize(size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return vehicle_msgs_msg_InsData_max_cdr_typesize;
}

size_t vehicle_msgs::msg::InsData::getCdrSerializedSize(const vehicle_msgs::msg::InsData& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;
    current_alignment += std_msgs::msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    // longitude (double)
    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);
    // latitude (double)
    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);
    // altitude (float)
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    // yaw, pitch, roll (float x3)
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    // vx, vy, vt, psd (float x4)
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    // r, p, q (float x3)
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    // gps_fix_state, satellite_num, gps_id, nav_state (uint8 x4)
    current_alignment += 4;
    // nav_fault_code (uint16)
    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);
    // is_valid (bool)
    current_alignment += 1;
    // timestamp (double)
    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);
    return current_alignment - initial_alignment;
}

void vehicle_msgs::msg::InsData::serialize(eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_header;
    scdr << m_longitude;
    scdr << m_latitude;
    scdr << m_altitude;
    scdr << m_yaw;
    scdr << m_pitch;
    scdr << m_roll;
    scdr << m_vx;
    scdr << m_vy;
    scdr << m_vt;
    scdr << m_psd;
    scdr << m_r;
    scdr << m_p;
    scdr << m_q;
    scdr << m_gps_fix_state;
    scdr << m_satellite_num;
    scdr << m_gps_id;
    scdr << m_nav_state;
    scdr << m_nav_fault_code;
    scdr << m_is_valid;
    scdr << m_timestamp;
}

void vehicle_msgs::msg::InsData::deserialize(eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_header;
    dcdr >> m_longitude;
    dcdr >> m_latitude;
    dcdr >> m_altitude;
    dcdr >> m_yaw;
    dcdr >> m_pitch;
    dcdr >> m_roll;
    dcdr >> m_vx;
    dcdr >> m_vy;
    dcdr >> m_vt;
    dcdr >> m_psd;
    dcdr >> m_r;
    dcdr >> m_p;
    dcdr >> m_q;
    dcdr >> m_gps_fix_state;
    dcdr >> m_satellite_num;
    dcdr >> m_gps_id;
    dcdr >> m_nav_state;
    dcdr >> m_nav_fault_code;
    dcdr >> m_is_valid;
    dcdr >> m_timestamp;
}

// getter/setter implementations
void vehicle_msgs::msg::InsData::header(const std_msgs::msg::Header& _header) { m_header = _header; }
void vehicle_msgs::msg::InsData::header(std_msgs::msg::Header&& _header) { m_header = std::move(_header); }
const std_msgs::msg::Header& vehicle_msgs::msg::InsData::header() const { return m_header; }
std_msgs::msg::Header& vehicle_msgs::msg::InsData::header() { return m_header; }

void vehicle_msgs::msg::InsData::longitude(double _v) { m_longitude = _v; }
double vehicle_msgs::msg::InsData::longitude() const { return m_longitude; }
double& vehicle_msgs::msg::InsData::longitude() { return m_longitude; }

void vehicle_msgs::msg::InsData::latitude(double _v) { m_latitude = _v; }
double vehicle_msgs::msg::InsData::latitude() const { return m_latitude; }
double& vehicle_msgs::msg::InsData::latitude() { return m_latitude; }

void vehicle_msgs::msg::InsData::altitude(float _v) { m_altitude = _v; }
float vehicle_msgs::msg::InsData::altitude() const { return m_altitude; }
float& vehicle_msgs::msg::InsData::altitude() { return m_altitude; }

void vehicle_msgs::msg::InsData::yaw(float _v) { m_yaw = _v; }
float vehicle_msgs::msg::InsData::yaw() const { return m_yaw; }
float& vehicle_msgs::msg::InsData::yaw() { return m_yaw; }

void vehicle_msgs::msg::InsData::pitch(float _v) { m_pitch = _v; }
float vehicle_msgs::msg::InsData::pitch() const { return m_pitch; }
float& vehicle_msgs::msg::InsData::pitch() { return m_pitch; }

void vehicle_msgs::msg::InsData::roll(float _v) { m_roll = _v; }
float vehicle_msgs::msg::InsData::roll() const { return m_roll; }
float& vehicle_msgs::msg::InsData::roll() { return m_roll; }

void vehicle_msgs::msg::InsData::vx(float _v) { m_vx = _v; }
float vehicle_msgs::msg::InsData::vx() const { return m_vx; }
float& vehicle_msgs::msg::InsData::vx() { return m_vx; }

void vehicle_msgs::msg::InsData::vy(float _v) { m_vy = _v; }
float vehicle_msgs::msg::InsData::vy() const { return m_vy; }
float& vehicle_msgs::msg::InsData::vy() { return m_vy; }

void vehicle_msgs::msg::InsData::vt(float _v) { m_vt = _v; }
float vehicle_msgs::msg::InsData::vt() const { return m_vt; }
float& vehicle_msgs::msg::InsData::vt() { return m_vt; }

void vehicle_msgs::msg::InsData::psd(float _v) { m_psd = _v; }
float vehicle_msgs::msg::InsData::psd() const { return m_psd; }
float& vehicle_msgs::msg::InsData::psd() { return m_psd; }

void vehicle_msgs::msg::InsData::r(float _v) { m_r = _v; }
float vehicle_msgs::msg::InsData::r() const { return m_r; }
float& vehicle_msgs::msg::InsData::r() { return m_r; }

void vehicle_msgs::msg::InsData::p(float _v) { m_p = _v; }
float vehicle_msgs::msg::InsData::p() const { return m_p; }
float& vehicle_msgs::msg::InsData::p() { return m_p; }

void vehicle_msgs::msg::InsData::q(float _v) { m_q = _v; }
float vehicle_msgs::msg::InsData::q() const { return m_q; }
float& vehicle_msgs::msg::InsData::q() { return m_q; }

void vehicle_msgs::msg::InsData::gps_fix_state(uint8_t _v) { m_gps_fix_state = _v; }
uint8_t vehicle_msgs::msg::InsData::gps_fix_state() const { return m_gps_fix_state; }
uint8_t& vehicle_msgs::msg::InsData::gps_fix_state() { return m_gps_fix_state; }

void vehicle_msgs::msg::InsData::satellite_num(uint8_t _v) { m_satellite_num = _v; }
uint8_t vehicle_msgs::msg::InsData::satellite_num() const { return m_satellite_num; }
uint8_t& vehicle_msgs::msg::InsData::satellite_num() { return m_satellite_num; }

void vehicle_msgs::msg::InsData::gps_id(uint8_t _v) { m_gps_id = _v; }
uint8_t vehicle_msgs::msg::InsData::gps_id() const { return m_gps_id; }
uint8_t& vehicle_msgs::msg::InsData::gps_id() { return m_gps_id; }

void vehicle_msgs::msg::InsData::nav_state(uint8_t _v) { m_nav_state = _v; }
uint8_t vehicle_msgs::msg::InsData::nav_state() const { return m_nav_state; }
uint8_t& vehicle_msgs::msg::InsData::nav_state() { return m_nav_state; }

void vehicle_msgs::msg::InsData::nav_fault_code(uint16_t _v) { m_nav_fault_code = _v; }
uint16_t vehicle_msgs::msg::InsData::nav_fault_code() const { return m_nav_fault_code; }
uint16_t& vehicle_msgs::msg::InsData::nav_fault_code() { return m_nav_fault_code; }

void vehicle_msgs::msg::InsData::is_valid(bool _v) { m_is_valid = _v; }
bool vehicle_msgs::msg::InsData::is_valid() const { return m_is_valid; }
bool& vehicle_msgs::msg::InsData::is_valid() { return m_is_valid; }

void vehicle_msgs::msg::InsData::timestamp(double _v) { m_timestamp = _v; }
double vehicle_msgs::msg::InsData::timestamp() const { return m_timestamp; }
double& vehicle_msgs::msg::InsData::timestamp() { return m_timestamp; }

size_t vehicle_msgs::msg::InsData::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return vehicle_msgs_msg_InsData_max_key_cdr_typesize;
}

bool vehicle_msgs::msg::InsData::isKeyDefined()
{
    return false;
}

void vehicle_msgs::msg::InsData::serializeKey(eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}
