// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file InsData.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_VEHICLE_MSGS_MSG_INSDATA_H_
#define _FAST_DDS_GENERATED_VEHICLE_MSGS_MSG_INSDATA_H_

#include "Header.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(InsData_SOURCE)
#define InsData_DllAPI __declspec( dllexport )
#else
#define InsData_DllAPI __declspec( dllimport )
#endif // InsData_SOURCE
#else
#define InsData_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define InsData_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima

namespace vehicle_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure InsData defined by the user in the IDL file.
         * @ingroup INSDATA
         */
        class InsData
        {
        public:

            eProsima_user_DllExport InsData();
            eProsima_user_DllExport ~InsData();
            eProsima_user_DllExport InsData(const InsData& x);
            eProsima_user_DllExport InsData(InsData&& x) noexcept;
            eProsima_user_DllExport InsData& operator =(const InsData& x);
            eProsima_user_DllExport InsData& operator =(InsData&& x) noexcept;
            eProsima_user_DllExport bool operator ==(const InsData& x) const;
            eProsima_user_DllExport bool operator !=(const InsData& x) const;

            eProsima_user_DllExport void header(const std_msgs::msg::Header& _header);
            eProsima_user_DllExport void header(std_msgs::msg::Header&& _header);
            eProsima_user_DllExport const std_msgs::msg::Header& header() const;
            eProsima_user_DllExport std_msgs::msg::Header& header();

            eProsima_user_DllExport void longitude(double _longitude);
            eProsima_user_DllExport double longitude() const;
            eProsima_user_DllExport double& longitude();

            eProsima_user_DllExport void latitude(double _latitude);
            eProsima_user_DllExport double latitude() const;
            eProsima_user_DllExport double& latitude();

            eProsima_user_DllExport void altitude(float _altitude);
            eProsima_user_DllExport float altitude() const;
            eProsima_user_DllExport float& altitude();

            eProsima_user_DllExport void yaw(float _yaw);
            eProsima_user_DllExport float yaw() const;
            eProsima_user_DllExport float& yaw();

            eProsima_user_DllExport void pitch(float _pitch);
            eProsima_user_DllExport float pitch() const;
            eProsima_user_DllExport float& pitch();

            eProsima_user_DllExport void roll(float _roll);
            eProsima_user_DllExport float roll() const;
            eProsima_user_DllExport float& roll();

            eProsima_user_DllExport void vx(float _vx);
            eProsima_user_DllExport float vx() const;
            eProsima_user_DllExport float& vx();

            eProsima_user_DllExport void vy(float _vy);
            eProsima_user_DllExport float vy() const;
            eProsima_user_DllExport float& vy();

            eProsima_user_DllExport void vt(float _vt);
            eProsima_user_DllExport float vt() const;
            eProsima_user_DllExport float& vt();

            eProsima_user_DllExport void psd(float _psd);
            eProsima_user_DllExport float psd() const;
            eProsima_user_DllExport float& psd();

            eProsima_user_DllExport void r(float _r);
            eProsima_user_DllExport float r() const;
            eProsima_user_DllExport float& r();

            eProsima_user_DllExport void p(float _p);
            eProsima_user_DllExport float p() const;
            eProsima_user_DllExport float& p();

            eProsima_user_DllExport void q(float _q);
            eProsima_user_DllExport float q() const;
            eProsima_user_DllExport float& q();

            eProsima_user_DllExport void gps_fix_state(uint8_t _gps_fix_state);
            eProsima_user_DllExport uint8_t gps_fix_state() const;
            eProsima_user_DllExport uint8_t& gps_fix_state();

            eProsima_user_DllExport void satellite_num(uint8_t _satellite_num);
            eProsima_user_DllExport uint8_t satellite_num() const;
            eProsima_user_DllExport uint8_t& satellite_num();

            eProsima_user_DllExport void gps_id(uint8_t _gps_id);
            eProsima_user_DllExport uint8_t gps_id() const;
            eProsima_user_DllExport uint8_t& gps_id();

            eProsima_user_DllExport void nav_state(uint8_t _nav_state);
            eProsima_user_DllExport uint8_t nav_state() const;
            eProsima_user_DllExport uint8_t& nav_state();

            eProsima_user_DllExport void nav_fault_code(uint16_t _nav_fault_code);
            eProsima_user_DllExport uint16_t nav_fault_code() const;
            eProsima_user_DllExport uint16_t& nav_fault_code();

            eProsima_user_DllExport void is_valid(bool _is_valid);
            eProsima_user_DllExport bool is_valid() const;
            eProsima_user_DllExport bool& is_valid();

            eProsima_user_DllExport void timestamp(double _timestamp);
            eProsima_user_DllExport double timestamp() const;
            eProsima_user_DllExport double& timestamp();

            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);
            eProsima_user_DllExport static size_t getCdrSerializedSize(const vehicle_msgs::msg::InsData& data, size_t current_alignment = 0);
            eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr& cdr) const;
            eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr& cdr);
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);
            eProsima_user_DllExport static bool isKeyDefined();
            eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr& scdr) const;

        private:
            std_msgs::msg::Header m_header;
            double m_longitude;
            double m_latitude;
            float m_altitude;
            float m_yaw;
            float m_pitch;
            float m_roll;
            float m_vx;
            float m_vy;
            float m_vt;
            float m_psd;
            float m_r;
            float m_p;
            float m_q;
            uint8_t m_gps_fix_state;
            uint8_t m_satellite_num;
            uint8_t m_gps_id;
            uint8_t m_nav_state;
            uint16_t m_nav_fault_code;
            bool m_is_valid;
            double m_timestamp;
        };
    } // namespace msg
} // namespace vehicle_msgs

#endif // _FAST_DDS_GENERATED_VEHICLE_MSGS_MSG_INSDATA_H_
